# frozen_string_literal: true

# == InvitationMailer
#
# @!group Mailers
#
# Sends custom invitation emails to users,
# generated by {UserInvitationService}.
#
# === Use
#   InvitationMailer.custom_invite(user, inviter, "Join now!").deliver_later
#
# === Or
#   InvitationMailer.custom_invite(user, inviter, message).deliver_now
#
# @!endgroup
#

class InvitationMailer < ApplicationMailer
    def custom_invite(user, inviter, message)
        @user = user
        @inviter = inviter
        @message = message.presence || t("We invite you to join our learning community!")

        mail(to: @user.email, subject: t("You have been invited to The Ruby Train platform.")) do |format|
            format.text { render layout: "mailer" }
            format.html { render layout: "mailer" }
        end
    end
end
