# frozen_string_literal: true

# == InvitationMailer
#
# @!group Mailers
#
# Sends custom invitation emails to users,
# generated by {UserInvitationService}.
#
# === Use
#   InvitationMailer.custom_invite(user, inviter, "¡Únete!").deliver_later
#
# @!endgroup
#

class PurgeSuspendedUsersJob < ApplicationJob
  queue_as :default

  def perform
    threshold = 30.days.ago
    User.suspended.where("updated_at < ?", threshold).find_each do |user|
      user.destroy!
    end
  end
end
